#' -----------------------------------------------------------------------------
#' Aim: Gather processed tracking data for Vultures, covering different studies,
#' for testing purposes. Study-specific data is generated by running an offline
#' simulation of the developed study-level workflow, which involves a series of
#' Apps developed in this project. Source code for these apps are available
#' locally and the offline workflow was set up in a separate R project
#' ("Workflows_simulator"), also available locally.
#' ----------------------------------------------------------------------------

# ----------------------- #
# ----     Preamble   -----
# ----------------------- #

require(fs)
require(move2)
require(dplyr)
require(readr)
require(lubridate)
require(withr)
require(httr2)


options(dplyr.width = Inf)

source("../../Workflows_simulator/fcts_apps_wrappers.R")
source("../../Workflows_simulator/helpers.r")
source("../../Workflows_simulator/fcts_study_level_workflows.R")
source("tests/app-testing-helpers.r")

proj_key <- get_proj_key()
app_key <- get_app_key()

mvbk_creds <- httr2::secret_read_rds("../../Workflows_simulator/mvbk_creds.rds", key = I(proj_key))



apps_paths <- list(
  mvbkloc = "../Movebank-Loc-move2/",
  localsolar = "../Convert-Times/",
  stand = "../Standardise_Formats_and_Calculate_Basic_Statistics/",
  fetch_acc = "../Fetch_and_Merge_Acceleration_to_Locations/",
  classif = "../Behavioural_Classification_for_Vultures/"
)



# ----------------------------------------------- #
# ----    Run study-level Workflows (offline)  -----
# ----------------------------------------------- #

tm_end <- as.POSIXct("2024-03-15 00:00:00", tz = "UTC")

nam <- study_level_wf(
  apps_paths = apps_paths,
  mvbk_usr = mvbk_creds$scavengersonpatrol$usr, 
  mvbk_pwd = mvbk_creds$scavengersonpatrol$pwd,
  study_name = "AVulture Namibia SOP", 
  animal_ids = c("GA_5404", "TO_6485", "GA_6581", "GA_6594", "TO_6032"),
  tm_start = tm_end - days(15),
  tm_end = tm_end, 
  loc_tm_thin_mins = 3
)


gaia <- study_level_wf(
  apps_paths = apps_paths,
  mvbk_usr = mvbk_creds$scavengersonpatrol$usr, 
  mvbk_pwd = mvbk_creds$scavengersonpatrol$pwd,
  study_name = 2065208399, # "GAIA Vulture", 
  animal_ids = c("V032", "V038", "V043", "V045", "V039", "V061"),
  tm_start = tm_end - days(15),
  tm_end = tm_end, 
  loc_tm_thin_mins = 3, 
  acc_tm_thin_mins = 1
)


movebank_remove_credentials()

sa_vfa <- study_level_wf(
  apps_paths = apps_paths,
  mvbk_usr = mvbk_creds$mlmackenzie$usr, 
  mvbk_pwd = mvbk_creds$mlmackenzie$pwd,
  study_name = "South Africa vultures VfA MPIAB", 
  animal_ids = c("Bateleur_8889", "Bateleur_8887", "White-headed_8888"),
  tm_start = tm_end - days(15),
  tm_end = tm_end
)

wcs <- study_level_wf(
  apps_paths = apps_paths,
  mvbk_usr = mvbk_creds$mlmackenzie$usr, 
  mvbk_pwd = mvbk_creds$mlmackenzie$pwd,
  study_name = "WCS Ruaha-Katavi Vultures", 
  animal_ids = c("AW196499", "B175706", "AW196500" ),
  tm_start = tm_end - days(30),
  tm_end = tm_end, 
  alt_col = "", 
  temp_col = ""
)


ken_tnz <- study_level_wf(
  apps_paths = apps_paths,
  mvbk_usr = mvbk_creds$mlmackenzie$usr, 
  mvbk_pwd = mvbk_creds$mlmackenzie$pwd,
  study_name = 103394406, #"Gyps africanus Kendall Tanzania$", 
  animal_ids = c("ST1104A", "ST1008A", "ST1035A", "C175593", "A234556", "ST970A",
                 "ST1111A", "ST1081A", "ST1087A", "STZim", "163116Z", "ST1085A", 
                 "B181263", "C181261", "ST1066A", "D33004", "E175591", "A234562", 
                 "D151400", "A234559", "A234561"
  ),
  tm_start = tm_end - days(30),
  tm_end = tm_end, 
  temp_col = ""
)


savahn <- study_level_wf(
  apps_paths = apps_paths,
  mvbk_usr = mvbk_creds$mlmackenzie$usr, 
  mvbk_pwd = mvbk_creds$mlmackenzie$pwd,
  study_name = "Savannah-MEFT", 
  animal_ids = c("SAV-4360-A", "SAV-4384-A", "SAV-4355-B", "SAV-4356-A", 
                 "SAV-4386-A", "SAV-4357-A", "SAV-4358-A"),
  tm_start = tm_end - days(30),
  tm_end = tm_end, 
  alt_col = "", 
  temp_col = ""
)





# ---------------------------------------------------------------- #
# ----  Combine test sets in list and export to encrypted file -----
# ---------------------------------------------------------------- #

test_sets <- list(
  nam = nam,
  gaia = gaia,
  sa_vfa = sa_vfa,
  wcs = wcs,
  savahn = savahn,
  ken_tnz = ken_tnz
)

httr2::secret_write_rds(test_sets, path = "data/raw/vult_test_data.rds", key = I(app_key))

# subset for unit testing
unit_test_sets <- test_sets[c("nam", "wcs", "savahn", "ken_tnz")]
httr2::secret_write_rds(unit_test_sets, path = "tests/testthat/data/vult_unit_test_data.rds", key = I(app_key))
